name: pconv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.9.0
  - torchvision=0.24.0
  - pytorch-lightning=2.5.6
  - torchmetrics=1.8.2
  - scikit-learn=1.7.2
  - numpy=2.2.6
  - matplotlib=3.10.7
  - python-dotenv=1.2.1
  - click=8.3.0
  - pip
  - pip:
      - libcirkit==0.2.1
      - comet_ml==3.54.0
      - simple_slurm==0.3.6
